version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      ports: "5436:5436"
      volumes: webflux_data:/var/lib/postgresql/data

volumes:
  webflux_data: